### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by BlaneG** [SLEEK-TOOLS/moja.canada#17]
I was following the instructions for building GCBM posted here:
https://github.com/moja-global/moja.canada

When attempting to create the Visual Studio solution I received the following CMake Error:
```
CMake Error at C:/Users/b_gra/Desktop/projects/2020/moja-global/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  moja.modules.gdal/CMakeLists.txt:7 (find_package)
```

**Comment by BlaneG** [comment]
The issue appears to be a result of fmtlib not being installed.  I was able to resolve this issue by running `vcpkg.exe install fmt:x64-windows`.

**Comment by shubhamkarande13** [comment]
@BlaneG Thank you for opening this issue. We have made the required changes in the moja global docs. 

@mfellows Could you please close this issue?

Thank you!
