### ISSUE TITLE
The second CMake command doesn't work

### ISSUE THREAD

**Issue by shubhamkarande13** [SLEEK-TOOLS/moja.canada#23]
The second CMake command in the `README.md` doesn't work anymore due to the path changes in [this commit](https://github.com/moja-global/moja.canada/commit/311bf0553023e2db0b08be5340dbbf0941442bb5).

This is not consistent with the [tutorial video](https://youtu.be/y5fbzDPOjkc).

Thanks to @mavneeK for reporting this!

**Comment by shubhamkarande13** [comment]
@mfellows @aornugent 
Could you please look into this?

**Comment by mfellows** [comment]
The cmake line in README.md isn't really meant to be taken literally, since people could have all kinds of different directory setups on their machines (i.e. maybe someone put vcpkg in c:\dev, or c:\utilities, or wherever) - closing this issue, but will add some explanatory text to the readme.
