### ISSUE TITLE
Update BUILD_TYPE from DEBUG to RELEASE in Dockerfile

### ISSUE THREAD

**Issue by Namyalg** [SLEEK-TOOLS/moja.canada#32]
The latest `moja.canada` image used the `GCBM example` produces this error

![image](https://user-images.githubusercontent.com/53875297/160224670-08cef6f9-f880-4204-aa7f-2a536eaf606e.png)

In the `/usr/local/lib`, `lib.moja.modules.cbm.so` is missing, as the build type debug is used.
These are the contents of `usr/local/lib` : [contents.txt](https://github.com/moja-global/moja.canada/files/8354676/contents.txt)

@aornugent pointed out that changing the `BUILD_TYPE` from `DEBUG` to `RELEASE` will solve the error,

@HarshCasper could you make the change

**Comment by aornugent** [comment]
Closed by https://github.com/moja-global/moja.canada/pull/33
